version: '3'

tasks:
  default:
    cmds:
      - task --list
    desc: Show all available tasks
    silent: true

  run:
    cmds:
      - poetry run streamlit run src/calculator.py
    desc: Run the mortgage calculator
    silent: true

  test:
    cmds:
      - poetry run pytest tests/test_utils_finance.py
    desc: Run finance utility tests
    silent: true
